In [1]:
import numpy as np


In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F

In [10]:
z=np.zeros(10)

In [11]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
z=np.zeros((10,10))
print('%d bytes' % (z.itemsize*z.size))

800 bytes


In [21]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

Exception: File `'python -c "import numpy; numpy.info(numpy.add)".py'` not found.

In [23]:
z=np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [43]:
z = z[::-2]
print(z)

[49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11]


In [48]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

# 11 - 20




In [58]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.random.random((3,3,3))

array([[[0.48262596, 0.28774704, 0.37273098],
        [0.70481854, 0.28070076, 0.829131  ],
        [0.78662774, 0.08196243, 0.24565243]],

       [[0.64929906, 0.84355722, 0.96658468],
        [0.47922414, 0.75777667, 0.14522025],
        [0.14034476, 0.96836219, 0.20003564]],

       [[0.87439794, 0.1853876 , 0.99523452],
        [0.30882214, 0.06961167, 0.19398372],
        [0.11242764, 0.74962241, 0.11170796]]])

In [86]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
zmin, zmax

(0.0143127288427074, 0.9960848541040637)

In [90]:
z = np.random.random(30)
m = z.mean()
m

0.4725653552544591

In [110]:
z = np.ones((10,10))
z[2:-1, 2:-2] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [116]:
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode = 'constant', constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [121]:
z = np.diag(1+np.arange(4), k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [130]:
z = np.zeros((8,8), dtype=int)
z[1::2,::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])